### ISSUE TITLE
Double click in videoplayer on vk.com close tab.

### ISSUE THREAD

**Issue by chuvak2033** [Smile4ever/Double-Click-On-Page-Closes-Tab#3]
In most video players, double clicking maximaze/minimizes the video, on vk.com in videoplayer double click close tab.
[[video for example]](https://vk.com/video-56422188_456239033)

**Comment by Smile4ever** [comment]
Thank you for opening this issue.

document.activeElement.innerHTML.includes("video") might solve this issue; I will try it out and hopefully create a new version with the fix. I'll keep you posted.

**Comment by Smile4ever** [comment]
Version 1.0.0 fixes this issue
